language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
script: ./cibuild

before_script:
 - chmod +x cibuild

after_success:
  - openssl aes-256-cbc -K $encrypted_75777d40d7e6_key -iv $encrypted_75777d40d7e6_iv -in .travis/id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa # this key should have push access
  - eval "$(ssh-agent -s)"
  - ssh-add id_rsa
  - git remote add deploy ssh://deploy@akmiller.co.uk/opt/deploy/site
  - git push deploy deploy-$TRAVIS_BRANCH

# branch whitelist
branches:
  only:
  - dev    # test the gh-pages branch
  - master:
  # - /pages-(.*)/ # test every branch which starts with "pages-"

addons:
  ssh_known_hosts: akmiller.co.uk

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

exclude: [vendor]
