# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Andrew Miller
# tagline:          'What do you see?'
description:      'Hello! This is my little corner of the internet, I hope to start writing & posting more.'
url:              https://akmiller.co.uk/

author:
  name:           'Andrew Miller'
  email:           info@akmiller.co.uk

paginate:         5

# Custom vars
# version:          2.0.0

# github:
#   repo:           https://github.com/poole/hyde


github: https://github.com/nanorepublica
linkedin: https://uk.linkedin.com/in/akmiller89
twitter: https://twitter.com/nanorepublica
cv: /public/CV.pdf
rss: /atom.xml

exclude: [old, notes.md]

gems: [jekyll-paginate]
